/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './login-page';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/auth';
import * as import10 from 'ionic-angular/components/loading/loading';
import * as import11 from 'ionic-angular/components/toast/toast';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from 'ionic-angular/components/toolbar/toolbar';
import * as import15 from 'ionic-angular/components/navbar/navbar';
import * as import16 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import17 from 'ionic-angular/components/content/content';
import * as import18 from 'ionic-angular/components/grid/grid';
import * as import19 from 'ionic-angular/components/list/list';
import * as import20 from 'ionic-angular/components/item/item';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from 'ionic-angular/components/label/label';
import * as import23 from 'ionic-angular/components/icon/icon';
import * as import24 from '@angular/forms/src/directives/ng_model';
import * as import25 from '@angular/forms/src/directives/ng_control_status';
import * as import26 from 'ionic-angular/components/input/input';
import * as import27 from 'ionic-angular/components/button/button';
import * as import28 from 'ionic-angular/config/config';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import32 from 'ionic-angular/components/app/app';
import * as import33 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import34 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import35 from 'ionic-angular/util/keyboard';
import * as import36 from '@angular/core/src/zone/ng_zone';
import * as import37 from 'ionic-angular/components/tabs/tabs';
import * as import38 from 'ionic-angular/gestures/gesture-controller';
import * as import39 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import40 from 'ionic-angular/util/form';
import * as import41 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import42 from 'ionic-angular/platform/platform';
import * as import43 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import44 from '@angular/forms/src/directives/ng_control';
var renderType_LoginPage_Host:import0.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LoginPage_0_4:import3.LoginPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('login-page',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginPage_0_4 = new import3.LoginPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.Auth),this.parentInjector.get(import10.LoadingController),this.parentInjector.get(import11.ToastController));
    this._appEl_0.initComponent(this._LoginPage_0_4,[],compView_0);
    compView_0.create(this._LoginPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,[],{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import13.ComponentFactory<import3.LoginPage> = new import13.ComponentFactory<import3.LoginPage>('login-page',viewFactory_LoginPage_Host0,import3.LoginPage);
const styles_LoginPage:any[] = [];
var renderType_LoginPage:import0.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import3.LoginPage> {
  _el_0:any;
  _Header_0_3:import14.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import15.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import16.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import17.Content;
  _text_10:any;
  _el_11:any;
  _Row_11_3:import18.Row;
  _text_12:any;
  _el_13:any;
  _Col_13_3:import18.Col;
  _text_14:any;
  _el_15:any;
  _List_15_3:import19.List;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _Item_17_4:import20.Item;
  _ItemContent_17_5:import20.ItemContent;
  _query_Label_17_0:import21.QueryList<any>;
  _query_Button_17_1:import21.QueryList<any>;
  _query_Icon_17_2:import21.QueryList<any>;
  _text_18:any;
  _el_19:any;
  _Label_19_3:import22.Label;
  _el_20:any;
  _Icon_20_3:import23.Icon;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _NgModel_22_4:import24.NgModel;
  _NgControl_22_5:any;
  _NgControlStatus_22_6:import25.NgControlStatus;
  _TextInput_22_7:import26.TextInput;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _Item_25_4:import20.Item;
  _ItemContent_25_5:import20.ItemContent;
  _query_Label_25_0:import21.QueryList<any>;
  _query_Button_25_1:import21.QueryList<any>;
  _query_Icon_25_2:import21.QueryList<any>;
  _text_26:any;
  _el_27:any;
  _Label_27_3:import22.Label;
  _el_28:any;
  _Icon_28_3:import23.Icon;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _NgModel_30_4:import24.NgModel;
  _NgControl_30_5:any;
  _NgControlStatus_30_6:import25.NgControlStatus;
  _TextInput_30_7:import26.TextInput;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  /*private*/ _appEl_33:import2.AppElement;
  _Item_33_4:import20.Item;
  _ItemContent_33_5:import20.ItemContent;
  _query_Label_33_0:import21.QueryList<any>;
  _query_Button_33_1:import21.QueryList<any>;
  _query_Icon_33_2:import21.QueryList<any>;
  _text_34:any;
  _el_35:any;
  _Label_35_3:import22.Label;
  _el_36:any;
  _Icon_36_3:import23.Icon;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import2.AppElement;
  _NgModel_38_4:import24.NgModel;
  _NgControl_38_5:any;
  _NgControlStatus_38_6:import25.NgControlStatus;
  _TextInput_38_7:import26.TextInput;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  /*private*/ _appEl_42:import2.AppElement;
  _Button_42_4:import27.Button;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import14.Header(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','kebap');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import31.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import15.Navbar(this.parentInjector.get(import32.App),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import33.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import16.ToolbarTitle(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import14.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'FoodWare Mobil',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n \n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import34.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import17.Content(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import35.Keyboard),this.parentInjector.get(import36.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import37.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n \n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','firm-form');
    this._Row_11_3 = new import18.Row();
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-col',(null as any));
    this._Col_13_3 = new import18.Col();
    this._text_14 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_15,'inset','');
    this._List_15_3 = new import19.List(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_15),this.renderer,this.parentInjector.get(import38.GestureController));
    this._text_16 = this.renderer.createText(this._el_15,'\n \n              ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','item item-block');
    this._appEl_17 = new import2.AppElement(17,15,this,this._el_17);
    var compView_17:any = import39.viewFactory_Item0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Item_17_4 = new import20.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_17),this.renderer);
    this._ItemContent_17_5 = new import20.ItemContent();
    this._query_Label_17_0 = new import21.QueryList<any>();
    this._query_Button_17_1 = new import21.QueryList<any>();
    this._query_Icon_17_2 = new import21.QueryList<any>();
    this._appEl_17.initComponent(this._Item_17_4,[],compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_19_3 = new import22.Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_19),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._el_20 = this.renderer.createElement(this._el_19,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_20,'name','person');
    this.renderer.setElementAttribute(this._el_20,'role','img');
    this._Icon_20_3 = new import23.Icon(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_20),this.renderer);
    this._text_21 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_22,'placeholder','Kullanıcı Adı');
    this.renderer.setElementAttribute(this._el_22,'type','text');
    this._appEl_22 = new import2.AppElement(22,17,this,this._el_22);
    var compView_22:any = import41.viewFactory_TextInput0(this.viewUtils,this.injector(22),this._appEl_22);
    this._NgModel_22_4 = new import24.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_22_5 = this._NgModel_22_4;
    this._NgControlStatus_22_6 = new import25.NgControlStatus(this._NgControl_22_5);
    this._TextInput_22_7 = new import26.TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import40.Form),this._Item_17_4,this.parentInjector.get(import32.App),this.parentInjector.get(import42.Platform),new import29.ElementRef(this._el_22),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_22_5);
    this._appEl_22.initComponent(this._TextInput_22_7,[],compView_22);
    compView_22.create(this._TextInput_22_7,[],(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._query_Label_17_0.reset([this._Label_19_3]);
    this._Item_17_4.contentLabel = this._query_Label_17_0.first;
    compView_17.create(this._Item_17_4,[
      [],
      [].concat([this._el_19]),
      [].concat([
        this._text_18,
        this._text_21,
        this._text_23
      ]
      ),
      [].concat([this._el_22]),
      []
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(this._el_15,'\n \n              ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_15,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','item item-block');
    this._appEl_25 = new import2.AppElement(25,15,this,this._el_25);
    var compView_25:any = import39.viewFactory_Item0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Item_25_4 = new import20.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_25),this.renderer);
    this._ItemContent_25_5 = new import20.ItemContent();
    this._query_Label_25_0 = new import21.QueryList<any>();
    this._query_Button_25_1 = new import21.QueryList<any>();
    this._query_Icon_25_2 = new import21.QueryList<any>();
    this._appEl_25.initComponent(this._Item_25_4,[],compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_27_3 = new import22.Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_27),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._el_28 = this.renderer.createElement(this._el_27,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_28,'name','lock');
    this.renderer.setElementAttribute(this._el_28,'role','img');
    this._Icon_28_3 = new import23.Icon(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_30,'placeholder','Parola');
    this.renderer.setElementAttribute(this._el_30,'type','password');
    this._appEl_30 = new import2.AppElement(30,25,this,this._el_30);
    var compView_30:any = import41.viewFactory_TextInput0(this.viewUtils,this.injector(30),this._appEl_30);
    this._NgModel_30_4 = new import24.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_30_5 = this._NgModel_30_4;
    this._NgControlStatus_30_6 = new import25.NgControlStatus(this._NgControl_30_5);
    this._TextInput_30_7 = new import26.TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import40.Form),this._Item_25_4,this.parentInjector.get(import32.App),this.parentInjector.get(import42.Platform),new import29.ElementRef(this._el_30),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_30_5);
    this._appEl_30.initComponent(this._TextInput_30_7,[],compView_30);
    compView_30.create(this._TextInput_30_7,[],(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._query_Label_25_0.reset([this._Label_27_3]);
    this._Item_25_4.contentLabel = this._query_Label_25_0.first;
    compView_25.create(this._Item_25_4,[
      [],
      [].concat([this._el_27]),
      [].concat([
        this._text_26,
        this._text_29,
        this._text_31
      ]
      ),
      [].concat([this._el_30]),
      []
    ]
    ,(null as any));
    this._text_32 = this.renderer.createText(this._el_15,'\n\n               ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_15,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','firm item item-block');
    this._appEl_33 = new import2.AppElement(33,15,this,this._el_33);
    var compView_33:any = import39.viewFactory_Item0(this.viewUtils,this.injector(33),this._appEl_33);
    this._Item_33_4 = new import20.Item(this.parentInjector.get(import40.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_33),this.renderer);
    this._ItemContent_33_5 = new import20.ItemContent();
    this._query_Label_33_0 = new import21.QueryList<any>();
    this._query_Button_33_1 = new import21.QueryList<any>();
    this._query_Icon_33_2 = new import21.QueryList<any>();
    this._appEl_33.initComponent(this._Item_33_4,[],compView_33);
    this._text_34 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_35_3 = new import22.Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_35),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._el_36 = this.renderer.createElement(this._el_35,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_36,'name','briefcase');
    this.renderer.setElementAttribute(this._el_36,'role','img');
    this._Icon_36_3 = new import23.Icon(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_36),this.renderer);
    this._text_37 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_38,'placeholder','Firma Kodu');
    this.renderer.setElementAttribute(this._el_38,'type','text');
    this._appEl_38 = new import2.AppElement(38,33,this,this._el_38);
    var compView_38:any = import41.viewFactory_TextInput0(this.viewUtils,this.injector(38),this._appEl_38);
    this._NgModel_38_4 = new import24.NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_38_5 = this._NgModel_38_4;
    this._NgControlStatus_38_6 = new import25.NgControlStatus(this._NgControl_38_5);
    this._TextInput_38_7 = new import26.TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import40.Form),this._Item_33_4,this.parentInjector.get(import32.App),this.parentInjector.get(import42.Platform),new import29.ElementRef(this._el_38),this.renderer,this._Content_9_4,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_38_5);
    this._appEl_38.initComponent(this._TextInput_38_7,[],compView_38);
    compView_38.create(this._TextInput_38_7,[],(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._query_Label_33_0.reset([this._Label_35_3]);
    this._Item_33_4.contentLabel = this._query_Label_33_0.first;
    compView_33.create(this._Item_33_4,[
      [],
      [].concat([this._el_35]),
      [].concat([
        this._text_34,
        this._text_37,
        this._text_39
      ]
      ),
      [].concat([this._el_38]),
      []
    ]
    ,(null as any));
    this._text_40 = this.renderer.createText(this._el_15,'\n \n            ',(null as any));
    this._text_41 = this.renderer.createText(this._el_13,'\n \n            ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_42,'block','');
    this.renderer.setElementAttribute(this._el_42,'class','login-button');
    this.renderer.setElementAttribute(this._el_42,'color','kebap');
    this.renderer.setElementAttribute(this._el_42,'ion-button','');
    this._appEl_42 = new import2.AppElement(42,13,this,this._el_42);
    var compView_42:any = import43.viewFactory_Button0(this.viewUtils,this.injector(42),this._appEl_42);
    this._Button_42_4 = new import27.Button((null as any),'',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_42),this.renderer);
    this._appEl_42.initComponent(this._Button_42_4,[],compView_42);
    this._text_43 = this.renderer.createText((null as any),'GİRİŞ',(null as any));
    compView_42.create(this._Button_42_4,[[].concat([this._text_43])],(null as any));
    this._text_44 = this.renderer.createText(this._el_13,'\n \n        ',(null as any));
    this._text_45 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_46 = this.renderer.createText((null as any),' \n',(null as any));
    compView_9.create(this._Content_9_4,[
      [],
      [].concat([
        this._text_10,
        this._el_11,
        this._text_46
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_22,'ngModelChange',this.eventHandler(this._handle_ngModelChange_22_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_22_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_22_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_30,'ngModelChange',this.eventHandler(this._handle_ngModelChange_30_0.bind(this)));
    this._expr_19 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_30_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_30_0.bind(this)));
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_38,'ngModelChange',this.eventHandler(this._handle_ngModelChange_38_0.bind(this)));
    this._expr_31 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_38_4.update.subscribe(this.eventHandler(this._handle_ngModelChange_38_0.bind(this)));
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_42,'click',this.eventHandler(this._handle_click_42_0.bind(this)));
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import15.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import14.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import23.Icon) && (20 === requestNodeIndex))) { return this._Icon_20_3; }
    if (((token === import22.Label) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Label_19_3; }
    if (((token === import24.NgModel) && (22 === requestNodeIndex))) { return this._NgModel_22_4; }
    if (((token === import44.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_5; }
    if (((token === import25.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_6; }
    if (((token === import26.TextInput) && (22 === requestNodeIndex))) { return this._TextInput_22_7; }
    if (((token === import20.Item) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Item_17_4; }
    if (((token === import20.ItemContent) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._ItemContent_17_5; }
    if (((token === import23.Icon) && (28 === requestNodeIndex))) { return this._Icon_28_3; }
    if (((token === import22.Label) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Label_27_3; }
    if (((token === import24.NgModel) && (30 === requestNodeIndex))) { return this._NgModel_30_4; }
    if (((token === import44.NgControl) && (30 === requestNodeIndex))) { return this._NgControl_30_5; }
    if (((token === import25.NgControlStatus) && (30 === requestNodeIndex))) { return this._NgControlStatus_30_6; }
    if (((token === import26.TextInput) && (30 === requestNodeIndex))) { return this._TextInput_30_7; }
    if (((token === import20.Item) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Item_25_4; }
    if (((token === import20.ItemContent) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._ItemContent_25_5; }
    if (((token === import23.Icon) && (36 === requestNodeIndex))) { return this._Icon_36_3; }
    if (((token === import22.Label) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Label_35_3; }
    if (((token === import24.NgModel) && (38 === requestNodeIndex))) { return this._NgModel_38_4; }
    if (((token === import44.NgControl) && (38 === requestNodeIndex))) { return this._NgControl_38_5; }
    if (((token === import25.NgControlStatus) && (38 === requestNodeIndex))) { return this._NgControlStatus_38_6; }
    if (((token === import26.TextInput) && (38 === requestNodeIndex))) { return this._TextInput_38_7; }
    if (((token === import20.Item) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Item_33_4; }
    if (((token === import20.ItemContent) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._ItemContent_33_5; }
    if (((token === import19.List) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._List_15_3; }
    if (((token === import27.Button) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Button_42_4; }
    if (((token === import18.Col) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Col_13_3; }
    if (((token === import18.Row) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Row_11_3; }
    if (((token === import17.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_0:any = 'kebap';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_2_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    const currVal_4:any = 'person';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Icon_20_3.name = currVal_4;
      this._expr_4 = currVal_4;
    }
    changes = (null as any);
    const currVal_7:any = this.context.username;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgModel_22_4.model = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._NgModel_22_4.ngOnChanges(changes); }
    const currVal_14:any = 'Kullanıcı Adı';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._TextInput_22_7.placeholder = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = 'text';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._TextInput_22_7.type = currVal_15;
      this._expr_15 = currVal_15;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_22_7.ngOnInit(); }
    const currVal_16:any = 'lock';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._Icon_28_3.name = currVal_16;
      this._expr_16 = currVal_16;
    }
    changes = (null as any);
    const currVal_19:any = this.context.password;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._NgModel_30_4.model = currVal_19;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_19,currVal_19);
      this._expr_19 = currVal_19;
    }
    if ((changes !== (null as any))) { this._NgModel_30_4.ngOnChanges(changes); }
    const currVal_26:any = 'Parola';
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._TextInput_30_7.placeholder = currVal_26;
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._TextInput_30_7.type = currVal_27;
      this._expr_27 = currVal_27;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_30_7.ngOnInit(); }
    const currVal_28:any = 'briefcase';
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this._Icon_36_3.name = currVal_28;
      this._expr_28 = currVal_28;
    }
    changes = (null as any);
    const currVal_31:any = this.context.firm;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this._NgModel_38_4.model = currVal_31;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_31,currVal_31);
      this._expr_31 = currVal_31;
    }
    if ((changes !== (null as any))) { this._NgModel_38_4.ngOnChanges(changes); }
    const currVal_38:any = 'Firma Kodu';
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this._TextInput_38_7.placeholder = currVal_38;
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = 'text';
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this._TextInput_38_7.type = currVal_39;
      this._expr_39 = currVal_39;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TextInput_38_7.ngOnInit(); }
    changed = false;
    const currVal_41:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this._Button_42_4.block = currVal_41;
      changed = true;
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = 'kebap';
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this._Button_42_4.color = currVal_42;
      changed = true;
      this._expr_42 = currVal_42;
    }
    if (changed) { this._appEl_42.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_17_1.dirty) {
        this._query_Button_17_1.reset([]);
        this._Item_17_4._buttons = this._query_Button_17_1;
        this._query_Button_17_1.notifyOnChanges();
      }
      if (this._query_Icon_17_2.dirty) {
        this._query_Icon_17_2.reset([]);
        this._Item_17_4._icons = this._query_Icon_17_2;
        this._query_Icon_17_2.notifyOnChanges();
      }
      if (this._query_Button_25_1.dirty) {
        this._query_Button_25_1.reset([]);
        this._Item_25_4._buttons = this._query_Button_25_1;
        this._query_Button_25_1.notifyOnChanges();
      }
      if (this._query_Icon_25_2.dirty) {
        this._query_Icon_25_2.reset([]);
        this._Item_25_4._icons = this._query_Icon_25_2;
        this._query_Icon_25_2.notifyOnChanges();
      }
      if (this._query_Button_33_1.dirty) {
        this._query_Button_33_1.reset([]);
        this._Item_33_4._buttons = this._query_Button_33_1;
        this._query_Button_33_1.notifyOnChanges();
      }
      if (this._query_Icon_33_2.dirty) {
        this._query_Icon_33_2.reset([]);
        this._Item_33_4._icons = this._query_Icon_33_2;
        this._query_Icon_33_2.notifyOnChanges();
      }
      this._TextInput_22_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_17_4.ngAfterContentInit(); }
      this._TextInput_30_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_25_4.ngAfterContentInit(); }
      this._TextInput_38_7.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_33_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_42_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = this._Icon_20_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_20,'hide',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._NgControlStatus_22_6.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_22,'ng-untouched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_22_6.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_22,'ng-touched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_22_6.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_22,'ng-pristine',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_22_6.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_22,'ng-dirty',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_22_6.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_22,'ng-valid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_22_6.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_22,'ng-invalid',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_17:any = this._Icon_28_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_28,'hide',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_20:any = this._NgControlStatus_30_6.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_30,'ng-untouched',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_30_6.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_30,'ng-touched',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_30_6.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_30,'ng-pristine',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_30_6.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_30,'ng-dirty',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_30_6.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_30,'ng-valid',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_30_6.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_30,'ng-invalid',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_29:any = this._Icon_36_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_36,'hide',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_32:any = this._NgControlStatus_38_6.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_38,'ng-untouched',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_38_6.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_38,'ng-touched',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_38_6.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_38,'ng-pristine',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_38_6.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_38,'ng-dirty',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_38_6.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_38,'ng-valid',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_38_6.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_38,'ng-invalid',currVal_37);
      this._expr_37 = currVal_37;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_20_3.ngOnDestroy();
    this._NgModel_22_4.ngOnDestroy();
    this._TextInput_22_7.ngOnDestroy();
    this._Icon_28_3.ngOnDestroy();
    this._NgModel_30_4.ngOnDestroy();
    this._TextInput_30_7.ngOnDestroy();
    this._Icon_36_3.ngOnDestroy();
    this._NgModel_38_4.ngOnDestroy();
    this._TextInput_38_7.ngOnDestroy();
    this._Content_9_4.ngOnDestroy();
  }
  private _handle_ngModelChange_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.username = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_38_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.firm = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.login()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('C:/Users/cano/Desktop/FoodWare/authApp/.tmp/pages/login-page/login-page.html',0,import12.ViewEncapsulation.None,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}