/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './report';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '../../providers/getFirms';
import * as import11 from 'ionic-angular/components/loading/loading';
import * as import12 from '../../providers/auth';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from 'ionic-angular/components/toolbar/toolbar';
import * as import16 from 'ionic-angular/components/navbar/navbar';
import * as import17 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from 'ionic-angular/components/button/button';
import * as import20 from 'ionic-angular/components/icon/icon';
import * as import21 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import22 from 'ionic-angular/components/content/content';
import * as import23 from '@angular/common/src/directives/ng_if';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import30 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import31 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import32 from 'ionic-angular/util/keyboard';
import * as import33 from '@angular/core/src/zone/ng_zone';
import * as import34 from 'ionic-angular/components/tabs/tabs';
import * as import35 from '@angular/core/src/linker/template_ref';
import * as import36 from 'ionic-angular/components/list/list';
import * as import37 from 'ionic-angular/components/item/item';
import * as import38 from 'ionic-angular/components/list/list-header';
import * as import39 from '@angular/common/src/directives/ng_for';
import * as import40 from 'ionic-angular/gestures/gesture-controller';
import * as import41 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import42 from 'ionic-angular/util/form';
import * as import43 from '@angular/core/src/change_detection/differs/iterable_differs';
var renderType_ReportsPage_Host:import0.RenderComponentType = (null as any);
class _View_ReportsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ReportsPage_0_4:import3.ReportsPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ReportsPage_Host0,renderType_ReportsPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-report',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ReportsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ReportsPage_0_4 = new import3.ReportsPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.FirmService),this.parentInjector.get(import11.LoadingController),this.parentInjector.get(import12.Auth));
    this._appEl_0.initComponent(this._ReportsPage_0_4,[],compView_0);
    compView_0.create(this._ReportsPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ReportsPage) && (0 === requestNodeIndex))) { return this._ReportsPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ReportsPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ReportsPage_Host === (null as any))) { (renderType_ReportsPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_ReportsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ReportsPageNgFactory:import14.ComponentFactory<import3.ReportsPage> = new import14.ComponentFactory<import3.ReportsPage>('page-report',viewFactory_ReportsPage_Host0,import3.ReportsPage);
const styles_ReportsPage:any[] = [];
var renderType_ReportsPage:import0.RenderComponentType = (null as any);
class _View_ReportsPage0 extends import1.AppView<import3.ReportsPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import15.Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _Navbar_3_4:import16.Navbar;
  _text_4:any;
  _el_5:any;
  _ToolbarItem_5_3:import17.ToolbarItem;
  _query_Button_5_0:import18.QueryList<any>;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _Button_7_4:import19.Button;
  _text_8:any;
  _el_9:any;
  _Icon_9_3:import20.Icon;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _ToolbarTitle_13_4:import21.ToolbarTitle;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _ToolbarItem_16_3:import17.ToolbarItem;
  _query_Button_16_0:import18.QueryList<any>;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _Button_18_4:import19.Button;
  _text_19:any;
  _el_20:any;
  _Icon_20_3:import20.Icon;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _Content_26_4:import22.Content;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import23.NgIf;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _anchor_32:any;
  /*private*/ _appEl_32:import2.AppElement;
  _TemplateRef_32_5:any;
  _NgIf_32_6:import23.NgIf;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _anchor_36:any;
  /*private*/ _appEl_36:import2.AppElement;
  _TemplateRef_36_5:any;
  _NgIf_36_6:import23.NgIf;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _anchor_40:any;
  /*private*/ _appEl_40:import2.AppElement;
  _TemplateRef_40_5:any;
  _NgIf_40_6:import23.NgIf;
  _text_41:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ReportsPage0,renderType_ReportsPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','report');
    this._Header_1_3 = new import15.Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n	',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','kebap');
    this.renderer.setElementAttribute(this._el_3,'hideBackButton','true');
    this.renderer.setElementAttribute(this._el_3,'primary','');
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import27.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import16.Navbar(this.parentInjector.get(import28.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4,[],compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this._ToolbarItem_5_3 = new import17.ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import15.Toolbar,(null as any)),this._Navbar_3_4);
    this._query_Button_5_0 = new import18.QueryList<any>();
    this._text_6 = this.renderer.createText(this._el_5,'\n			',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'icon-only','');
    this.renderer.setElementAttribute(this._el_7,'ion-button','');
    this._appEl_7 = new import2.AppElement(7,5,this,this._el_7);
    var compView_7:any = import29.viewFactory_Button0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Button_7_4 = new import19.Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_7),this.renderer);
    this._appEl_7.initComponent(this._Button_7_4,[],compView_7);
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_9,'name','arrow-back');
    this.renderer.setElementAttribute(this._el_9,'role','img');
    this._Icon_9_3 = new import20.Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_9),this.renderer);
    this._text_10 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_7.create(this._Button_7_4,[[].concat([
        this._text_8,
        this._el_9,
        this._text_10
      ]
    )],(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n\n		',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_13 = new import2.AppElement(13,3,this,this._el_13);
    var compView_13:any = import30.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(13),this._appEl_13);
    this._ToolbarTitle_13_4 = new import21.ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import15.Toolbar,(null as any)),this._Navbar_3_4);
    this._appEl_13.initComponent(this._ToolbarTitle_13_4,[],compView_13);
    this._text_14 = this.renderer.createText((null as any),'',(null as any));
    compView_13.create(this._ToolbarTitle_13_4,[[].concat([this._text_14])],(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n\n		',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_16,'end','');
    this._ToolbarItem_16_3 = new import17.ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_16),this.renderer,this.parentInjector.get(import15.Toolbar,(null as any)),this._Navbar_3_4);
    this._query_Button_16_0 = new import18.QueryList<any>();
    this._text_17 = this.renderer.createText(this._el_16,'\n			',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'icon-only','');
    this.renderer.setElementAttribute(this._el_18,'ion-button','');
    this._appEl_18 = new import2.AppElement(18,16,this,this._el_18);
    var compView_18:any = import29.viewFactory_Button0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Button_18_4 = new import19.Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_18),this.renderer);
    this._appEl_18.initComponent(this._Button_18_4,[],compView_18);
    this._text_19 = this.renderer.createText((null as any),' \n              ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_20,'name','power');
    this.renderer.setElementAttribute(this._el_20,'role','img');
    this._Icon_20_3 = new import20.Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_20),this.renderer);
    this._text_21 = this.renderer.createText((null as any),'\n              ',(null as any));
      compView_18.create(this._Button_18_4,[[].concat([
        this._text_19,
        this._el_20,
        this._text_21
      ]
    )],(null as any));
    this._text_22 = this.renderer.createText(this._el_16,'\n		',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n	',(null as any));
    compView_3.create(this._Navbar_3_4,[
      [],
      [],
      [].concat([this._el_16]),
      [].concat([
        this._text_4,
        this._el_5,
        this._text_12,
        this._el_13,
        this._text_15,
        this._text_23
      ]
      )
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_25 = this.renderer.createText(parentRenderNode,'\n\n\n\n',(null as any));
    this._el_26 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_26 = new import2.AppElement(26,(null as any),this,this._el_26);
    var compView_26:any = import31.viewFactory_Content0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Content_26_4 = new import22.Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_26),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import32.Keyboard),this.parentInjector.get(import33.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import34.Tabs,(null as any)));
    this._appEl_26.initComponent(this._Content_26_4,[],compView_26);
    this._text_27 = this.renderer.createText((null as any),'\n	',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_28 = new import2.AppElement(28,26,this,this._anchor_28);
    this._TemplateRef_28_5 = new import35.TemplateRef_(this._appEl_28,viewFactory_ReportsPage1);
    this._NgIf_28_6 = new import23.NgIf(this._appEl_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'br',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n	',(null as any));
    this._anchor_32 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_32 = new import2.AppElement(32,26,this,this._anchor_32);
    this._TemplateRef_32_5 = new import35.TemplateRef_(this._appEl_32,viewFactory_ReportsPage3);
    this._NgIf_32_6 = new import23.NgIf(this._appEl_32.vcRef,this._TemplateRef_32_5);
    this._text_33 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'br',(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n	',(null as any));
    this._anchor_36 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_36 = new import2.AppElement(36,26,this,this._anchor_36);
    this._TemplateRef_36_5 = new import35.TemplateRef_(this._appEl_36,viewFactory_ReportsPage5);
    this._NgIf_36_6 = new import23.NgIf(this._appEl_36.vcRef,this._TemplateRef_36_5);
    this._text_37 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'br',(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n	',(null as any));
    this._anchor_40 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_40 = new import2.AppElement(40,26,this,this._anchor_40);
    this._TemplateRef_40_5 = new import35.TemplateRef_(this._appEl_40,viewFactory_ReportsPage7);
    this._NgIf_40_6 = new import23.NgIf(this._appEl_40.vcRef,this._TemplateRef_40_5);
    this._text_41 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_26.create(this._Content_26_4,[
      [],
      [].concat([
        this._text_27,
        this._appEl_28,
        this._text_29,
        this._el_30,
        this._text_31,
        this._appEl_32,
        this._text_33,
        this._el_34,
        this._text_35,
        this._appEl_36,
        this._text_37,
        this._el_38,
        this._text_39,
        this._appEl_40,
        this._text_41
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._anchor_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._anchor_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._anchor_40,
      this._text_41
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.Icon) && (9 === requestNodeIndex))) { return this._Icon_9_3; }
    if (((token === import19.Button) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Button_7_4; }
    if (((token === import17.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarItem_5_3; }
    if (((token === import21.ToolbarTitle) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ToolbarTitle_13_4; }
    if (((token === import20.Icon) && (20 === requestNodeIndex))) { return this._Icon_20_3; }
    if (((token === import19.Button) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Button_18_4; }
    if (((token === import17.ToolbarItem) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._ToolbarItem_16_3; }
    if (((token === import16.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Navbar_3_4; }
    if (((token === import15.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Header_1_3; }
    if (((token === import35.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import23.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6; }
    if (((token === import35.TemplateRef) && (32 === requestNodeIndex))) { return this._TemplateRef_32_5; }
    if (((token === import23.NgIf) && (32 === requestNodeIndex))) { return this._NgIf_32_6; }
    if (((token === import35.TemplateRef) && (36 === requestNodeIndex))) { return this._TemplateRef_36_5; }
    if (((token === import23.NgIf) && (36 === requestNodeIndex))) { return this._NgIf_36_6; }
    if (((token === import35.TemplateRef) && (40 === requestNodeIndex))) { return this._TemplateRef_40_5; }
    if (((token === import23.NgIf) && (40 === requestNodeIndex))) { return this._NgIf_40_6; }
    if (((token === import22.Content) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Content_26_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'kebap';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_3_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Navbar_3_4.hideBackButton = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_5:any = 'arrow-back';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Icon_9_3.name = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_9:any = 'power';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._Icon_20_3.name = currVal_9;
      this._expr_9 = currVal_9;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_26_4.ngOnInit(); }
    const currVal_12:any = (this.context.sales && (this.context.sales.length > 0));
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgIf_28_6.ngIf = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = (this.context.collectings && (this.context.collectings.length > 0));
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgIf_32_6.ngIf = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = (this.context.summary && (this.context.summary.length > 0));
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgIf_36_6.ngIf = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = (this.context.products && (this.context.products.length > 0));
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgIf_40_6.ngIf = currVal_15;
      this._expr_15 = currVal_15;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_7_4]);
        this._ToolbarItem_5_3._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if (this._query_Button_16_0.dirty) {
        this._query_Button_16_0.reset([this._Button_18_4]);
        this._ToolbarItem_16_3._buttons = this._query_Button_16_0;
        this._query_Button_16_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_7_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_18_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._Navbar_3_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Navbar_3_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_6:any = this._Icon_9_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_9,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'\n			',this.context.firmName,' ŞUBESİ\n		');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_14,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = this._Icon_20_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_20,'hide',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._Content_26_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_26,'statusbar-padding',currVal_11);
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_9_3.ngOnDestroy();
    this._Icon_20_3.ngOnDestroy();
    this._Content_26_4.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goBack()) !== false);
    return (true && pd_0);
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.logout()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ReportsPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ReportsPage> {
  if ((renderType_ReportsPage === (null as any))) { (renderType_ReportsPage = viewUtils.createRenderComponentType('C:/Users/cano/Desktop/FoodWare/authApp/.tmp/pages/report/report.html',0,import13.ViewEncapsulation.None,styles_ReportsPage,{})); }
  return new _View_ReportsPage0(viewUtils,parentInjector,declarationEl);
}
class _View_ReportsPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _List_2_3:import36.List;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Item_4_4:import37.Item;
  _ListHeader_4_5:import38.ListHeader;
  _query_Label_4_0:import18.QueryList<any>;
  _query_Button_4_1:import18.QueryList<any>;
  _query_Icon_4_2:import18.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _TemplateRef_10_5:any;
  _NgFor_10_6:import39.NgFor;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _Item_12_4:import37.Item;
  _ItemContent_12_5:import37.ItemContent;
  _query_Label_12_0:import18.QueryList<any>;
  _query_Button_12_1:import18.QueryList<any>;
  _query_Icon_12_2:import18.QueryList<any>;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ReportsPage1,renderType_ReportsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-list',(null as any));
    this._List_2_3 = new import36.List(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer,this.parent.parentInjector.get(import40.GestureController));
    this._text_3 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','item');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import41.viewFactory_Item0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Item_4_4 = new import37.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer);
    this._ListHeader_4_5 = new import38.ListHeader(this.parent.parentInjector.get(import24.Config),this.renderer,new import25.ElementRef(this._el_4),(null as any));
    this._query_Label_4_0 = new import18.QueryList<any>();
    this._query_Button_4_1 = new import18.QueryList<any>();
    this._query_Icon_4_2 = new import18.QueryList<any>();
    this._appEl_4.initComponent(this._Item_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'h1',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Satış',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_4_0.reset([]);
    this._Item_4_4.contentLabel = this._query_Label_4_0.first;
    compView_4.create(this._Item_4_4,[
      [],
      [],
      [].concat([
        this._text_5,
        this._el_6,
        this._text_8
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_10 = new import2.AppElement(10,2,this,this._anchor_10);
    this._TemplateRef_10_5 = new import35.TemplateRef_(this._appEl_10,viewFactory_ReportsPage2);
    this._NgFor_10_6 = new import39.NgFor(this._appEl_10.vcRef,this._TemplateRef_10_5,this.parent.parentInjector.get(import43.IterableDiffers),this.parent.ref);
    this._text_11 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_12 = this.renderer.createElement(this._el_2,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','item item-block');
    this._appEl_12 = new import2.AppElement(12,2,this,this._el_12);
    var compView_12:any = import41.viewFactory_Item0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Item_12_4 = new import37.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_12),this.renderer);
    this._ItemContent_12_5 = new import37.ItemContent();
    this._query_Label_12_0 = new import18.QueryList<any>();
    this._query_Button_12_1 = new import18.QueryList<any>();
    this._query_Icon_12_2 = new import18.QueryList<any>();
    this._appEl_12.initComponent(this._Item_12_4,[],compView_12);
    this._text_13 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_12_0.reset([]);
    this._Item_12_4.contentLabel = this._query_Label_12_0.first;
    compView_12.create(this._Item_12_4,[
      [],
      [],
      [].concat([this._text_13]),
      [],
      []
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Item) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Item_4_4; }
    if (((token === import38.ListHeader) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ListHeader_4_5; }
    if (((token === import35.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import39.NgFor) && (10 === requestNodeIndex))) { return this._NgFor_10_6; }
    if (((token === import37.Item) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Item_12_4; }
    if (((token === import37.ItemContent) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ItemContent_12_5; }
    if (((token === import36.List) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._List_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.sales;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_10_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_10_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_10_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_1.dirty) {
        this._query_Button_4_1.reset([]);
        this._Item_4_4._buttons = this._query_Button_4_1;
        this._query_Button_4_1.notifyOnChanges();
      }
      if (this._query_Icon_4_2.dirty) {
        this._query_Icon_4_2.reset([]);
        this._Item_4_4._icons = this._query_Icon_4_2;
        this._query_Icon_4_2.notifyOnChanges();
      }
      if (this._query_Button_12_1.dirty) {
        this._query_Button_12_1.reset([]);
        this._Item_12_4._buttons = this._query_Button_12_1;
        this._query_Button_12_1.notifyOnChanges();
      }
      if (this._query_Icon_12_2.dirty) {
        this._query_Icon_12_2.reset([]);
        this._Item_12_4._icons = this._query_Icon_12_2;
        this._query_Icon_12_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_12_4.ngAfterContentInit(); }
    }
    const currVal_1:any = import4.interpolate(1,'TOPLAM: ',this.parent.context.getSalesSum(),' TL');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_13,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ReportsPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ReportsPage1(viewUtils,parentInjector,declarationEl);
}
class _View_ReportsPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import37.Item;
  _ItemContent_0_5:import37.ItemContent;
  _query_Label_0_0:import18.QueryList<any>;
  _query_Button_0_1:import18.QueryList<any>;
  _query_Icon_0_2:import18.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ReportsPage2,renderType_ReportsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import41.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import37.Item(this.parent.parent.parentInjector.get(import42.Form),this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import37.ItemContent();
    this._query_Label_0_0 = new import18.QueryList<any>();
    this._query_Button_0_1 = new import18.QueryList<any>();
    this._query_Icon_0_2 = new import18.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_0_0.reset([]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [],
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_4,
        this._el_5,
        this._text_7
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Item_0_4; }
    if (((token === import37.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ItemContent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.tip,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.tutar,' TL');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_6,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ReportsPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ReportsPage2(viewUtils,parentInjector,declarationEl);
}
class _View_ReportsPage3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _List_2_3:import36.List;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Item_4_4:import37.Item;
  _ListHeader_4_5:import38.ListHeader;
  _query_Label_4_0:import18.QueryList<any>;
  _query_Button_4_1:import18.QueryList<any>;
  _query_Icon_4_2:import18.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _TemplateRef_10_5:any;
  _NgFor_10_6:import39.NgFor;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _Item_12_4:import37.Item;
  _ItemContent_12_5:import37.ItemContent;
  _query_Label_12_0:import18.QueryList<any>;
  _query_Button_12_1:import18.QueryList<any>;
  _query_Icon_12_2:import18.QueryList<any>;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ReportsPage3,renderType_ReportsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-list',(null as any));
    this._List_2_3 = new import36.List(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer,this.parent.parentInjector.get(import40.GestureController));
    this._text_3 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','item');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import41.viewFactory_Item0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Item_4_4 = new import37.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer);
    this._ListHeader_4_5 = new import38.ListHeader(this.parent.parentInjector.get(import24.Config),this.renderer,new import25.ElementRef(this._el_4),(null as any));
    this._query_Label_4_0 = new import18.QueryList<any>();
    this._query_Button_4_1 = new import18.QueryList<any>();
    this._query_Icon_4_2 = new import18.QueryList<any>();
    this._appEl_4.initComponent(this._Item_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'h1',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Tahsilat',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_4_0.reset([]);
    this._Item_4_4.contentLabel = this._query_Label_4_0.first;
    compView_4.create(this._Item_4_4,[
      [],
      [],
      [].concat([
        this._text_5,
        this._el_6,
        this._text_8
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_10 = new import2.AppElement(10,2,this,this._anchor_10);
    this._TemplateRef_10_5 = new import35.TemplateRef_(this._appEl_10,viewFactory_ReportsPage4);
    this._NgFor_10_6 = new import39.NgFor(this._appEl_10.vcRef,this._TemplateRef_10_5,this.parent.parentInjector.get(import43.IterableDiffers),this.parent.ref);
    this._text_11 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_12 = this.renderer.createElement(this._el_2,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','item item-block');
    this._appEl_12 = new import2.AppElement(12,2,this,this._el_12);
    var compView_12:any = import41.viewFactory_Item0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Item_12_4 = new import37.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_12),this.renderer);
    this._ItemContent_12_5 = new import37.ItemContent();
    this._query_Label_12_0 = new import18.QueryList<any>();
    this._query_Button_12_1 = new import18.QueryList<any>();
    this._query_Icon_12_2 = new import18.QueryList<any>();
    this._appEl_12.initComponent(this._Item_12_4,[],compView_12);
    this._text_13 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_12_0.reset([]);
    this._Item_12_4.contentLabel = this._query_Label_12_0.first;
    compView_12.create(this._Item_12_4,[
      [],
      [],
      [].concat([this._text_13]),
      [],
      []
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Item) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Item_4_4; }
    if (((token === import38.ListHeader) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ListHeader_4_5; }
    if (((token === import35.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import39.NgFor) && (10 === requestNodeIndex))) { return this._NgFor_10_6; }
    if (((token === import37.Item) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Item_12_4; }
    if (((token === import37.ItemContent) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ItemContent_12_5; }
    if (((token === import36.List) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._List_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.collectings;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_10_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_10_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_10_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_1.dirty) {
        this._query_Button_4_1.reset([]);
        this._Item_4_4._buttons = this._query_Button_4_1;
        this._query_Button_4_1.notifyOnChanges();
      }
      if (this._query_Icon_4_2.dirty) {
        this._query_Icon_4_2.reset([]);
        this._Item_4_4._icons = this._query_Icon_4_2;
        this._query_Icon_4_2.notifyOnChanges();
      }
      if (this._query_Button_12_1.dirty) {
        this._query_Button_12_1.reset([]);
        this._Item_12_4._buttons = this._query_Button_12_1;
        this._query_Button_12_1.notifyOnChanges();
      }
      if (this._query_Icon_12_2.dirty) {
        this._query_Icon_12_2.reset([]);
        this._Item_12_4._icons = this._query_Icon_12_2;
        this._query_Icon_12_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_12_4.ngAfterContentInit(); }
    }
    const currVal_1:any = import4.interpolate(1,'TOPLAM: ',this.parent.context.getCollectingsSum(),' TL');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_13,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ReportsPage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ReportsPage3(viewUtils,parentInjector,declarationEl);
}
class _View_ReportsPage4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import37.Item;
  _ItemContent_0_5:import37.ItemContent;
  _query_Label_0_0:import18.QueryList<any>;
  _query_Button_0_1:import18.QueryList<any>;
  _query_Icon_0_2:import18.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ReportsPage4,renderType_ReportsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import41.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import37.Item(this.parent.parent.parentInjector.get(import42.Form),this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import37.ItemContent();
    this._query_Label_0_0 = new import18.QueryList<any>();
    this._query_Button_0_1 = new import18.QueryList<any>();
    this._query_Icon_0_2 = new import18.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_0_0.reset([]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [],
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_4,
        this._el_5,
        this._text_7
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Item_0_4; }
    if (((token === import37.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ItemContent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.tip,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.tutar,' TL');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_6,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ReportsPage4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ReportsPage4(viewUtils,parentInjector,declarationEl);
}
class _View_ReportsPage5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _List_2_3:import36.List;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Item_4_4:import37.Item;
  _ListHeader_4_5:import38.ListHeader;
  _query_Label_4_0:import18.QueryList<any>;
  _query_Button_4_1:import18.QueryList<any>;
  _query_Icon_4_2:import18.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _TemplateRef_10_5:any;
  _NgFor_10_6:import39.NgFor;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ReportsPage5,renderType_ReportsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-list',(null as any));
    this._List_2_3 = new import36.List(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer,this.parent.parentInjector.get(import40.GestureController));
    this._text_3 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','item');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import41.viewFactory_Item0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Item_4_4 = new import37.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer);
    this._ListHeader_4_5 = new import38.ListHeader(this.parent.parentInjector.get(import24.Config),this.renderer,new import25.ElementRef(this._el_4),(null as any));
    this._query_Label_4_0 = new import18.QueryList<any>();
    this._query_Button_4_1 = new import18.QueryList<any>();
    this._query_Icon_4_2 = new import18.QueryList<any>();
    this._appEl_4.initComponent(this._Item_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'h1',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Özet',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_4_0.reset([]);
    this._Item_4_4.contentLabel = this._query_Label_4_0.first;
    compView_4.create(this._Item_4_4,[
      [],
      [],
      [].concat([
        this._text_5,
        this._el_6,
        this._text_8
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_10 = new import2.AppElement(10,2,this,this._anchor_10);
    this._TemplateRef_10_5 = new import35.TemplateRef_(this._appEl_10,viewFactory_ReportsPage6);
    this._NgFor_10_6 = new import39.NgFor(this._appEl_10.vcRef,this._TemplateRef_10_5,this.parent.parentInjector.get(import43.IterableDiffers),this.parent.ref);
    this._text_11 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._text_12
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Item) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Item_4_4; }
    if (((token === import38.ListHeader) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ListHeader_4_5; }
    if (((token === import35.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import39.NgFor) && (10 === requestNodeIndex))) { return this._NgFor_10_6; }
    if (((token === import36.List) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._List_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.summary;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_10_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_10_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_10_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_1.dirty) {
        this._query_Button_4_1.reset([]);
        this._Item_4_4._buttons = this._query_Button_4_1;
        this._query_Button_4_1.notifyOnChanges();
      }
      if (this._query_Icon_4_2.dirty) {
        this._query_Icon_4_2.reset([]);
        this._Item_4_4._icons = this._query_Icon_4_2;
        this._query_Icon_4_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_4_4.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ReportsPage5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ReportsPage5(viewUtils,parentInjector,declarationEl);
}
class _View_ReportsPage6 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import37.Item;
  _ItemContent_0_5:import37.ItemContent;
  _query_Label_0_0:import18.QueryList<any>;
  _query_Button_0_1:import18.QueryList<any>;
  _query_Icon_0_2:import18.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ReportsPage6,renderType_ReportsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import41.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import37.Item(this.parent.parent.parentInjector.get(import42.Form),this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import37.ItemContent();
    this._query_Label_0_0 = new import18.QueryList<any>();
    this._query_Button_0_1 = new import18.QueryList<any>();
    this._query_Icon_0_2 = new import18.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_0_0.reset([]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [],
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_4,
        this._el_5,
        this._text_7
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Item_0_4; }
    if (((token === import37.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ItemContent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.adi,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.tutar,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_6,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ReportsPage6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ReportsPage6(viewUtils,parentInjector,declarationEl);
}
class _View_ReportsPage7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _List_2_3:import36.List;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Item_4_4:import37.Item;
  _ListHeader_4_5:import38.ListHeader;
  _query_Label_4_0:import18.QueryList<any>;
  _query_Button_4_1:import18.QueryList<any>;
  _query_Icon_4_2:import18.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _TemplateRef_10_5:any;
  _NgFor_10_6:import39.NgFor;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _Item_12_4:import37.Item;
  _ItemContent_12_5:import37.ItemContent;
  _query_Label_12_0:import18.QueryList<any>;
  _query_Button_12_1:import18.QueryList<any>;
  _query_Icon_12_2:import18.QueryList<any>;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ReportsPage7,renderType_ReportsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-list',(null as any));
    this._List_2_3 = new import36.List(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer,this.parent.parentInjector.get(import40.GestureController));
    this._text_3 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','item');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import41.viewFactory_Item0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Item_4_4 = new import37.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer);
    this._ListHeader_4_5 = new import38.ListHeader(this.parent.parentInjector.get(import24.Config),this.renderer,new import25.ElementRef(this._el_4),(null as any));
    this._query_Label_4_0 = new import18.QueryList<any>();
    this._query_Button_4_1 = new import18.QueryList<any>();
    this._query_Icon_4_2 = new import18.QueryList<any>();
    this._appEl_4.initComponent(this._Item_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'h1',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Ürünler',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_4_0.reset([]);
    this._Item_4_4.contentLabel = this._query_Label_4_0.first;
    compView_4.create(this._Item_4_4,[
      [],
      [],
      [].concat([
        this._text_5,
        this._el_6,
        this._text_8
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_10 = new import2.AppElement(10,2,this,this._anchor_10);
    this._TemplateRef_10_5 = new import35.TemplateRef_(this._appEl_10,viewFactory_ReportsPage8);
    this._NgFor_10_6 = new import39.NgFor(this._appEl_10.vcRef,this._TemplateRef_10_5,this.parent.parentInjector.get(import43.IterableDiffers),this.parent.ref);
    this._text_11 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_12 = this.renderer.createElement(this._el_2,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','item item-block');
    this._appEl_12 = new import2.AppElement(12,2,this,this._el_12);
    var compView_12:any = import41.viewFactory_Item0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Item_12_4 = new import37.Item(this.parent.parentInjector.get(import42.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_12),this.renderer);
    this._ItemContent_12_5 = new import37.ItemContent();
    this._query_Label_12_0 = new import18.QueryList<any>();
    this._query_Button_12_1 = new import18.QueryList<any>();
    this._query_Icon_12_2 = new import18.QueryList<any>();
    this._appEl_12.initComponent(this._Item_12_4,[],compView_12);
    this._text_13 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_12_0.reset([]);
    this._Item_12_4.contentLabel = this._query_Label_12_0.first;
    compView_12.create(this._Item_12_4,[
      [],
      [],
      [].concat([this._text_13]),
      [],
      []
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Item) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Item_4_4; }
    if (((token === import38.ListHeader) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ListHeader_4_5; }
    if (((token === import35.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import39.NgFor) && (10 === requestNodeIndex))) { return this._NgFor_10_6; }
    if (((token === import37.Item) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Item_12_4; }
    if (((token === import37.ItemContent) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ItemContent_12_5; }
    if (((token === import36.List) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._List_2_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.products;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_10_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_10_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_10_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_1.dirty) {
        this._query_Button_4_1.reset([]);
        this._Item_4_4._buttons = this._query_Button_4_1;
        this._query_Button_4_1.notifyOnChanges();
      }
      if (this._query_Icon_4_2.dirty) {
        this._query_Icon_4_2.reset([]);
        this._Item_4_4._icons = this._query_Icon_4_2;
        this._query_Icon_4_2.notifyOnChanges();
      }
      if (this._query_Button_12_1.dirty) {
        this._query_Button_12_1.reset([]);
        this._Item_12_4._buttons = this._query_Button_12_1;
        this._query_Button_12_1.notifyOnChanges();
      }
      if (this._query_Icon_12_2.dirty) {
        this._query_Icon_12_2.reset([]);
        this._Item_12_4._icons = this._query_Icon_12_2;
        this._query_Icon_12_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_12_4.ngAfterContentInit(); }
    }
    const currVal_1:any = import4.interpolate(1,'TOPLAM: ',this.parent.context.getProductsSum(),' TL');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_13,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ReportsPage7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ReportsPage7(viewUtils,parentInjector,declarationEl);
}
class _View_ReportsPage8 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import37.Item;
  _ItemContent_0_5:import37.ItemContent;
  _query_Label_0_0:import18.QueryList<any>;
  _query_Button_0_1:import18.QueryList<any>;
  _query_Icon_0_2:import18.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ReportsPage8,renderType_ReportsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import41.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import37.Item(this.parent.parent.parentInjector.get(import42.Form),this.parent.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import37.ItemContent();
    this._query_Label_0_0 = new import18.QueryList<any>();
    this._query_Button_0_1 = new import18.QueryList<any>();
    this._query_Icon_0_2 = new import18.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_0_0.reset([]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [],
      [],
      [].concat([
        this._text_1,
        this._el_2,
        this._text_4,
        this._el_5,
        this._text_7,
        this._el_8,
        this._text_10
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Item_0_4; }
    if (((token === import37.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ItemContent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.adi,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.miktar,' ADET');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_6,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.tutar,' TL');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_9,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ReportsPage8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ReportsPage8(viewUtils,parentInjector,declarationEl);
}