/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './firms';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '../../providers/getFirms';
import * as import11 from 'ionic-angular/components/loading/loading';
import * as import12 from '../../providers/auth';
import * as import13 from 'ionic-angular/components/toast/toast';
import * as import14 from 'ionic-angular/components/alert/alert';
import * as import15 from '@angular/core/src/metadata/view';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from 'ionic-angular/components/toolbar/toolbar';
import * as import18 from 'ionic-angular/components/navbar/navbar';
import * as import19 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import20 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from 'ionic-angular/components/button/button';
import * as import23 from 'ionic-angular/components/icon/icon';
import * as import24 from 'ionic-angular/components/content/content';
import * as import25 from 'ionic-angular/components/grid/grid';
import * as import26 from '@angular/common/src/directives/ng_if';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from '@angular/core/src/linker/element_ref';
import * as import29 from 'ionic-angular/navigation/view-controller';
import * as import30 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import31 from 'ionic-angular/components/app/app';
import * as import32 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import33 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import34 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import35 from 'ionic-angular/util/keyboard';
import * as import36 from '@angular/core/src/zone/ng_zone';
import * as import37 from 'ionic-angular/components/tabs/tabs';
import * as import38 from '@angular/core/src/linker/template_ref';
import * as import39 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import40 from '@angular/forms/src/directives/ng_control_status';
import * as import41 from 'ionic-angular/components/radio/radio-group';
import * as import42 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import43 from 'ionic-angular/components/list/list';
import * as import44 from 'ionic-angular/components/item/item';
import * as import45 from 'ionic-angular/components/list/list-header';
import * as import46 from 'ionic-angular/components/label/label';
import * as import47 from 'ionic-angular/components/radio/radio-button';
import * as import48 from 'ionic-angular/gestures/gesture-controller';
import * as import49 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import50 from 'ionic-angular/util/form';
import * as import51 from '../../node_modules/ionic-angular/components/radio/radio-button.ngfactory';
import * as import52 from '@angular/forms/src/directives/control_value_accessor';
import * as import53 from '@angular/forms/src/directives/ng_control';
import * as import54 from '@angular/forms/src/directives/control_container';
var renderType_FirmsPage_Host:import0.RenderComponentType = (null as any);
class _View_FirmsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _FirmsPage_0_4:import3.FirmsPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FirmsPage_Host0,renderType_FirmsPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-firms',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_FirmsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._FirmsPage_0_4 = new import3.FirmsPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.FirmService),this.parentInjector.get(import11.LoadingController),this.parentInjector.get(import12.Auth),this.parentInjector.get(import13.ToastController),this.parentInjector.get(import14.AlertController));
    this._appEl_0.initComponent(this._FirmsPage_0_4,[],compView_0);
    compView_0.create(this._FirmsPage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.FirmsPage) && (0 === requestNodeIndex))) { return this._FirmsPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_FirmsPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_FirmsPage_Host === (null as any))) { (renderType_FirmsPage_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,[],{})); }
  return new _View_FirmsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const FirmsPageNgFactory:import16.ComponentFactory<import3.FirmsPage> = new import16.ComponentFactory<import3.FirmsPage>('page-firms',viewFactory_FirmsPage_Host0,import3.FirmsPage);
const styles_FirmsPage:any[] = [];
var renderType_FirmsPage:import0.RenderComponentType = (null as any);
class _View_FirmsPage0 extends import1.AppView<import3.FirmsPage> {
  _el_0:any;
  _Header_0_3:import17.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import18.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import19.ToolbarTitle;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _ToolbarItem_10_3:import20.ToolbarItem;
  _query_Button_10_0:import21.QueryList<any>;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import2.AppElement;
  _Button_12_4:import22.Button;
  _el_13:any;
  _Icon_13_3:import23.Icon;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _Content_18_4:import24.Content;
  _text_19:any;
  _el_20:any;
  _Row_20_3:import25.Row;
  _text_21:any;
  _el_22:any;
  _Col_22_3:import25.Col;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import26.NgIf;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _Button_26_4:import22.Button;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FirmsPage0,renderType_FirmsPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import17.Header(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','kebap');
    this.renderer.setElementAttribute(this._el_2,'hideBackButton','');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import30.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Navbar(this.parentInjector.get(import31.App),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import32.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import19.ToolbarTitle(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import17.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n     ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n  ',(null as any));
      compView_4.create(this._ToolbarTitle_4_4,[[].concat([
        this._text_5,
        this._el_6,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_10,'start','');
    this._ToolbarItem_10_3 = new import20.ToolbarItem(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import17.Toolbar,(null as any)),this._Navbar_2_4);
    this._query_Button_10_0 = new import21.QueryList<any>();
    this._text_11 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'icon-only','');
    this.renderer.setElementAttribute(this._el_12,'ion-button','');
    this._appEl_12 = new import2.AppElement(12,10,this,this._el_12);
    var compView_12:any = import33.viewFactory_Button0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Button_12_4 = new import22.Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._Button_12_4,[],compView_12);
    this._el_13 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_13,'name','power');
    this.renderer.setElementAttribute(this._el_13,'role','img');
    this._Icon_13_3 = new import23.Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_13),this.renderer);
    compView_12.create(this._Button_12_4,[[].concat([this._el_13])],(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n  ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [].concat([this._el_10]),
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_9,
        this._text_15
      ]
      )
    ]
    ,(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_17 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_18 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_18 = new import2.AppElement(18,(null as any),this,this._el_18);
    var compView_18:any = import34.viewFactory_Content0(this.viewUtils,this.injector(18),this._appEl_18);
    this._Content_18_4 = new import24.Content(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import31.App),this.parentInjector.get(import35.Keyboard),this.parentInjector.get(import36.NgZone),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import37.Tabs,(null as any)));
    this._appEl_18.initComponent(this._Content_18_4,[],compView_18);
    this._text_19 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','login-form');
    this._Row_20_3 = new import25.Row();
    this._text_21 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'ion-col',(null as any));
    this._Col_22_3 = new import25.Col();
    this._text_23 = this.renderer.createText(this._el_22,'\n',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_22,(null as any));
    this._appEl_24 = new import2.AppElement(24,22,this,this._anchor_24);
    this._TemplateRef_24_5 = new import38.TemplateRef_(this._appEl_24,viewFactory_FirmsPage1);
    this._NgIf_24_6 = new import26.NgIf(this._appEl_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_22,'\n    ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_22,'button',(null as any));
    this.renderer.setElementAttribute(this._el_26,'block','');
    this.renderer.setElementAttribute(this._el_26,'class','firm-report');
    this.renderer.setElementAttribute(this._el_26,'color','kebap');
    this.renderer.setElementAttribute(this._el_26,'ion-button','');
    this._appEl_26 = new import2.AppElement(26,22,this,this._el_26);
    var compView_26:any = import33.viewFactory_Button0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Button_26_4 = new import22.Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_26),this.renderer);
    this._appEl_26.initComponent(this._Button_26_4,[],compView_26);
    this._text_27 = this.renderer.createText((null as any),'Raporları görüntüle',(null as any));
    compView_26.create(this._Button_26_4,[[].concat([this._text_27])],(null as any));
    this._text_28 = this.renderer.createText(this._el_22,'\n     ',(null as any));
    this._text_29 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_30 = this.renderer.createText((null as any),' \n',(null as any));
    compView_18.create(this._Content_18_4,[
      [],
      [].concat([
        this._text_19,
        this._el_20,
        this._text_30
      ]
      ),
      []
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_26,'click',this.eventHandler(this._handle_click_26_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarTitle_4_4; }
    if (((token === import23.Icon) && (13 === requestNodeIndex))) { return this._Icon_13_3; }
    if (((token === import22.Button) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Button_12_4; }
    if (((token === import20.ToolbarItem) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ToolbarItem_10_3; }
    if (((token === import18.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Navbar_2_4; }
    if (((token === import17.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Header_0_3; }
    if (((token === import38.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import26.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6; }
    if (((token === import22.Button) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Button_26_4; }
    if (((token === import25.Col) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Col_22_3; }
    if (((token === import25.Row) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Row_20_3; }
    if (((token === import24.Content) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Content_18_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    const currVal_0:any = 'kebap';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_2_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._Navbar_2_4.hideBackButton = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_6:any = 'power';
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Icon_13_3.name = currVal_6;
      this._expr_6 = currVal_6;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_18_4.ngOnInit(); }
    const currVal_9:any = (this.context.firms && (this.context.firms.length > 0));
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgIf_24_6.ngIf = currVal_9;
      this._expr_9 = currVal_9;
    }
    changed = false;
    const currVal_11:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Button_26_4.block = currVal_11;
      changed = true;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = 'kebap';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Button_26_4.color = currVal_12;
      changed = true;
      this._expr_12 = currVal_12;
    }
    if (changed) { this._appEl_26.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_10_0.dirty) {
        this._query_Button_10_0.reset([this._Button_12_4]);
        this._ToolbarItem_10_3._buttons = this._query_Button_10_0;
        this._query_Button_10_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_12_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_26_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'HOŞGELDİN ',this.context.username.toUpperCase(),'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_7,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = this._Icon_13_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_13,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Content_18_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_18,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_13_3.ngOnDestroy();
    this._Content_18_4.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.logout()) !== false);
    return (true && pd_0);
  }
  private _handle_click_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doRadio()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_FirmsPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.FirmsPage> {
  if ((renderType_FirmsPage === (null as any))) { (renderType_FirmsPage = viewUtils.createRenderComponentType('C:/Users/cano/Desktop/FoodWare/authApp/.tmp/pages/firms/firms.html',0,import15.ViewEncapsulation.None,styles_FirmsPage,{})); }
  return new _View_FirmsPage0(viewUtils,parentInjector,declarationEl);
}
class _View_FirmsPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _FormGroupDirective_2_3:import39.FormGroupDirective;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import40.NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  _RadioGroup_4_3:import41.RadioGroup;
  _NG_VALUE_ACCESSOR_4_4:any[];
  _FormControlName_4_5:import42.FormControlName;
  _NgControl_4_6:any;
  _NgControlStatus_4_7:import40.NgControlStatus;
  _List_4_8:import43.List;
  _query_ListHeader_4_0:import21.QueryList<any>;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _Item_6_4:import44.Item;
  _ListHeader_6_5:import45.ListHeader;
  _query_Label_6_0:import21.QueryList<any>;
  _query_Button_6_1:import21.QueryList<any>;
  _query_Icon_6_2:import21.QueryList<any>;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Item_9_4:import44.Item;
  _ItemContent_9_5:import44.ItemContent;
  _query_Label_9_0:import21.QueryList<any>;
  _query_Button_9_1:import21.QueryList<any>;
  _query_Icon_9_2:import21.QueryList<any>;
  _text_10:any;
  _el_11:any;
  _Label_11_3:import46.Label;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _RadioButton_14_4:import47.RadioButton;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _Item_17_4:import44.Item;
  _ItemContent_17_5:import44.ItemContent;
  _query_Label_17_0:import21.QueryList<any>;
  _query_Button_17_1:import21.QueryList<any>;
  _query_Icon_17_2:import21.QueryList<any>;
  _text_18:any;
  _el_19:any;
  _Label_19_3:import46.Label;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _RadioButton_22_4:import47.RadioButton;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _Item_25_4:import44.Item;
  _ItemContent_25_5:import44.ItemContent;
  _query_Label_25_0:import21.QueryList<any>;
  _query_Button_25_1:import21.QueryList<any>;
  _query_Icon_25_2:import21.QueryList<any>;
  _text_26:any;
  _el_27:any;
  _Label_27_3:import46.Label;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _RadioButton_30_4:import47.RadioButton;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_FirmsPage1,renderType_FirmsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'form',(null as any));
    this._FormGroupDirective_2_3 = new import39.FormGroupDirective((null as any),(null as any));
    this._ControlContainer_2_4 = this._FormGroupDirective_2_3;
    this._NgControlStatusGroup_2_5 = new import40.NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_4,'formControlName','langs');
    this.renderer.setElementAttribute(this._el_4,'radio-group','');
    this.renderer.setElementAttribute(this._el_4,'role','radiogroup');
    this._RadioGroup_4_3 = new import41.RadioGroup(this.renderer,new import28.ElementRef(this._el_4));
    this._NG_VALUE_ACCESSOR_4_4 = [this._RadioGroup_4_3];
    this._FormControlName_4_5 = new import42.FormControlName(this._ControlContainer_2_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_4_4);
    this._NgControl_4_6 = this._FormControlName_4_5;
    this._NgControlStatus_4_7 = new import40.NgControlStatus(this._NgControl_4_6);
    this._List_4_8 = new import43.List(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_4),this.renderer,this.parent.parentInjector.get(import48.GestureController));
    this._query_ListHeader_4_0 = new import21.QueryList<any>();
    this._text_5 = this.renderer.createText(this._el_4,'\n\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','item');
    this._appEl_6 = new import2.AppElement(6,4,this,this._el_6);
    var compView_6:any = import49.viewFactory_Item0(this.viewUtils,this.injector(6),this._appEl_6);
    this._Item_6_4 = new import44.Item(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_6),this.renderer);
    this._ListHeader_6_5 = new import45.ListHeader(this.parent.parentInjector.get(import27.Config),this.renderer,new import28.ElementRef(this._el_6),(null as any));
    this._query_Label_6_0 = new import21.QueryList<any>();
    this._query_Button_6_1 = new import21.QueryList<any>();
    this._query_Icon_6_2 = new import21.QueryList<any>();
    this._appEl_6.initComponent(this._Item_6_4,[],compView_6);
    this._text_7 = this.renderer.createText((null as any),'\n        Lütfen bir şube seçiniz\n      ',(null as any));
    this._query_Label_6_0.reset([]);
    this._Item_6_4.contentLabel = this._query_Label_6_0.first;
    compView_6.create(this._Item_6_4,[
      [],
      [],
      [].concat([this._text_7]),
      [],
      []
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n\n      ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','item item-block');
    this._appEl_9 = new import2.AppElement(9,4,this,this._el_9);
    var compView_9:any = import49.viewFactory_Item0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Item_9_4 = new import44.Item(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_9),this.renderer);
    this._ItemContent_9_5 = new import44.ItemContent();
    this._query_Label_9_0 = new import21.QueryList<any>();
    this._query_Button_9_1 = new import21.QueryList<any>();
    this._query_Icon_9_2 = new import21.QueryList<any>();
    this._appEl_9.initComponent(this._Item_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_11_3 = new import46.Label(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_11),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-radio',(null as any));
    this.renderer.setElementAttribute(this._el_14,'checked','true');
    this._appEl_14 = new import2.AppElement(14,9,this,this._el_14);
    var compView_14:any = import51.viewFactory_RadioButton0(this.viewUtils,this.injector(14),this._appEl_14);
    this._RadioButton_14_4 = new import47.RadioButton(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_14),this.renderer,this._Item_9_4,this._RadioGroup_4_3);
    this._appEl_14.initComponent(this._RadioButton_14_4,[],compView_14);
    compView_14.create(this._RadioButton_14_4,[],(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_9_0.reset([this._Label_11_3]);
    this._Item_9_4.contentLabel = this._query_Label_9_0.first;
    compView_9.create(this._Item_9_4,[
      [],
      [].concat([this._el_11]),
      [].concat([
        this._text_10,
        this._text_13,
        this._text_15
      ]
      ),
      [],
      [].concat([this._el_14])
    ]
    ,(null as any));
    this._text_16 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_4,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','item item-block');
    this._appEl_17 = new import2.AppElement(17,4,this,this._el_17);
    var compView_17:any = import49.viewFactory_Item0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Item_17_4 = new import44.Item(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_17),this.renderer);
    this._ItemContent_17_5 = new import44.ItemContent();
    this._query_Label_17_0 = new import21.QueryList<any>();
    this._query_Button_17_1 = new import21.QueryList<any>();
    this._query_Icon_17_2 = new import21.QueryList<any>();
    this._appEl_17.initComponent(this._Item_17_4,[],compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_19_3 = new import46.Label(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_19),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-radio',(null as any));
    this._appEl_22 = new import2.AppElement(22,17,this,this._el_22);
    var compView_22:any = import51.viewFactory_RadioButton0(this.viewUtils,this.injector(22),this._appEl_22);
    this._RadioButton_22_4 = new import47.RadioButton(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_22),this.renderer,this._Item_17_4,this._RadioGroup_4_3);
    this._appEl_22.initComponent(this._RadioButton_22_4,[],compView_22);
    compView_22.create(this._RadioButton_22_4,[],(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_17_0.reset([this._Label_19_3]);
    this._Item_17_4.contentLabel = this._query_Label_17_0.first;
    compView_17.create(this._Item_17_4,[
      [],
      [].concat([this._el_19]),
      [].concat([
        this._text_18,
        this._text_21,
        this._text_23
      ]
      ),
      [],
      [].concat([this._el_22])
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_4,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','item item-block');
    this._appEl_25 = new import2.AppElement(25,4,this,this._el_25);
    var compView_25:any = import49.viewFactory_Item0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Item_25_4 = new import44.Item(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_25),this.renderer);
    this._ItemContent_25_5 = new import44.ItemContent();
    this._query_Label_25_0 = new import21.QueryList<any>();
    this._query_Button_25_1 = new import21.QueryList<any>();
    this._query_Icon_25_2 = new import21.QueryList<any>();
    this._appEl_25.initComponent(this._Item_25_4,[],compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_27_3 = new import46.Label(this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_27),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-radio',(null as any));
    this._appEl_30 = new import2.AppElement(30,25,this,this._el_30);
    var compView_30:any = import51.viewFactory_RadioButton0(this.viewUtils,this.injector(30),this._appEl_30);
    this._RadioButton_30_4 = new import47.RadioButton(this.parent.parentInjector.get(import50.Form),this.parent.parentInjector.get(import27.Config),new import28.ElementRef(this._el_30),this.renderer,this._Item_25_4,this._RadioGroup_4_3);
    this._appEl_30.initComponent(this._RadioButton_30_4,[],compView_30);
    compView_30.create(this._RadioButton_30_4,[],(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_25_0.reset([this._Label_27_3]);
    this._Item_25_4.contentLabel = this._query_Label_25_0.first;
    compView_25.create(this._Item_25_4,[
      [],
      [].concat([this._el_27]),
      [].concat([
        this._text_26,
        this._text_29,
        this._text_31
      ]
      ),
      [],
      [].concat([this._el_30])
    ]
    ,(null as any));
    this._text_32 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._query_ListHeader_4_0.reset([this._ListHeader_6_5]);
    this._RadioGroup_4_3._header = this._query_ListHeader_4_0.first;
    this._text_33 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'submit',this.eventHandler(this._handle_submit_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_2,'reset',this.eventHandler(this._handle_reset_2_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_22,'click',this.eventHandler(this._handle_click_22_0.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import44.Item) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Item_6_4; }
    if (((token === import45.ListHeader) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ListHeader_6_5; }
    if (((token === import46.Label) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Label_11_3; }
    if (((token === import47.RadioButton) && (14 === requestNodeIndex))) { return this._RadioButton_14_4; }
    if (((token === import44.Item) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Item_9_4; }
    if (((token === import44.ItemContent) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._ItemContent_9_5; }
    if (((token === import46.Label) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Label_19_3; }
    if (((token === import47.RadioButton) && (22 === requestNodeIndex))) { return this._RadioButton_22_4; }
    if (((token === import44.Item) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Item_17_4; }
    if (((token === import44.ItemContent) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._ItemContent_17_5; }
    if (((token === import46.Label) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Label_27_3; }
    if (((token === import47.RadioButton) && (30 === requestNodeIndex))) { return this._RadioButton_30_4; }
    if (((token === import44.Item) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Item_25_4; }
    if (((token === import44.ItemContent) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._ItemContent_25_5; }
    if (((token === import41.RadioGroup) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._RadioGroup_4_3; }
    if (((token === import52.NG_VALUE_ACCESSOR) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NG_VALUE_ACCESSOR_4_4; }
    if (((token === import42.FormControlName) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._FormControlName_4_5; }
    if (((token === import53.NgControl) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgControl_4_6; }
    if (((token === import40.NgControlStatus) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._NgControlStatus_4_7; }
    if (((token === import43.List) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._List_4_8; }
    if (((token === import39.FormGroupDirective) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._FormGroupDirective_2_3; }
    if (((token === import54.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._ControlContainer_2_4; }
    if (((token === import40.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._NgControlStatusGroup_2_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_2:any = this.parent.context.langForm;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._FormGroupDirective_2_3.form = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['form'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._FormGroupDirective_2_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_9:any = 'langs';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._FormControlName_4_5.name = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._FormControlName_4_5.ngOnChanges(changes); }
    const currVal_18:any = this.parent.context.firms[0].id;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._RadioButton_14_4.value = currVal_18;
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = 'true';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._RadioButton_14_4.checked = currVal_19;
      this._expr_19 = currVal_19;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RadioButton_14_4.ngOnInit(); }
    const currVal_23:any = this.parent.context.firms[1].id;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._RadioButton_22_4.value = currVal_23;
      this._expr_23 = currVal_23;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RadioButton_22_4.ngOnInit(); }
    const currVal_27:any = this.parent.context.firms[2].id;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._RadioButton_30_4.value = currVal_27;
      this._expr_27 = currVal_27;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._RadioButton_30_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_6_1.dirty) {
        this._query_Button_6_1.reset([]);
        this._Item_6_4._buttons = this._query_Button_6_1;
        this._query_Button_6_1.notifyOnChanges();
      }
      if (this._query_Icon_6_2.dirty) {
        this._query_Icon_6_2.reset([]);
        this._Item_6_4._icons = this._query_Icon_6_2;
        this._query_Icon_6_2.notifyOnChanges();
      }
      if (this._query_Button_9_1.dirty) {
        this._query_Button_9_1.reset([]);
        this._Item_9_4._buttons = this._query_Button_9_1;
        this._query_Button_9_1.notifyOnChanges();
      }
      if (this._query_Icon_9_2.dirty) {
        this._query_Icon_9_2.reset([]);
        this._Item_9_4._icons = this._query_Icon_9_2;
        this._query_Icon_9_2.notifyOnChanges();
      }
      if (this._query_Button_17_1.dirty) {
        this._query_Button_17_1.reset([]);
        this._Item_17_4._buttons = this._query_Button_17_1;
        this._query_Button_17_1.notifyOnChanges();
      }
      if (this._query_Icon_17_2.dirty) {
        this._query_Icon_17_2.reset([]);
        this._Item_17_4._icons = this._query_Icon_17_2;
        this._query_Icon_17_2.notifyOnChanges();
      }
      if (this._query_Button_25_1.dirty) {
        this._query_Button_25_1.reset([]);
        this._Item_25_4._buttons = this._query_Button_25_1;
        this._query_Button_25_1.notifyOnChanges();
      }
      if (this._query_Icon_25_2.dirty) {
        this._query_Icon_25_2.reset([]);
        this._Item_25_4._icons = this._query_Icon_25_2;
        this._query_Icon_25_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_6_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_9_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_17_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_25_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RadioGroup_4_3.ngAfterContentInit(); }
    }
    const currVal_3:any = this._NgControlStatusGroup_2_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_2,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_2_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_2_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_2,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_2_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_2,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_2_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_2,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_2_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_2,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_10:any = this._NgControlStatus_4_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_4,'ng-untouched',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_4_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_4,'ng-touched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_4_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_4,'ng-pristine',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_4_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_4,'ng-dirty',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_4_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_4,'ng-valid',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_4_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_4,'ng-invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = import4.interpolate(1,'',this.parent.context.firms[0].adi,'');
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setText(this._text_12,currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_20:any = this._RadioButton_14_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_14,'radio-disabled',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = import4.interpolate(1,'',this.parent.context.firms[1].adi,'');
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_20,currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_24:any = this._RadioButton_22_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_22,'radio-disabled',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = import4.interpolate(1,'',this.parent.context.firms[2].adi,'');
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setText(this._text_28,currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_28:any = this._RadioButton_30_4._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_30,'radio-disabled',currVal_28);
      this._expr_28 = currVal_28;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RadioButton_14_4.ngOnDestroy();
    this._RadioButton_22_4.ngOnDestroy();
    this._RadioButton_30_4.ngOnDestroy();
    this._FormControlName_4_5.ngOnDestroy();
  }
  private _handle_submit_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_2_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_2_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_2_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this._appEl_14.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RadioButton_14_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_22_0($event:any):boolean {
    this._appEl_22.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RadioButton_22_4._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_30_0($event:any):boolean {
    this._appEl_30.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RadioButton_30_4._click($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_FirmsPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_FirmsPage1(viewUtils,parentInjector,declarationEl);
}